export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const CREATE_PROFILE = "CREATE_PROFILE"
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_POST";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const CREATE_ENCOURAGEMENT = "CREATE_ENCOURAGEMENT";
export const ENCOURAGEMENT_ERROR = "ENCOURAGEMENT_ERROR";
export const GET_POST = "GET_POST";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_ERROR = "POST_ERROR"

export const GET_POSTS = "GET_POSTS"
export const POSTS_ERROR = "POSTS_ERROR"

export const ADD_LIKE = "ADD_LIKE"

export const ADD_COMMENT = "ADD_COMMENT"
export const REMOVE_COMMENT = "REMOVE COMMENT"
export const COMMENT_ERROR = "COMMENT_ERRORS"
